blank_issues_enabled: false
contact_links:
  - name: Tardis Refined Community Discord
    url: https://discord.gg/XGsGNG7cCD
    about: The best place to receive quick answers to any questions you may have